# 배포용 yml 파일
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: datasource_url
    username: datasource_username
    password: datasource_password

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_batch_fetch_size: 500

  sql:
    init:
      mode: always

  redis:
    host: redis_host
    port: 6379
