oauth2:
  client-id: client_id
  client-secret: client_secret
  redirect-uri: redirect_uri
  token-uri: https://github.com/login/oauth/access_token
  user-info-uri: https://api.github.com/user
  login-uri: https://github.com/login/oauth/authorize

jwt:
  secretKey: secret_key
  refreshSecretKey: refresh_secret_key
  accessTokenExpiry : access_token_expiry
  refreshTokenExpiry : refresh_token_expiry
