oauth2:
  user:
    github:
      client-id: 305fd3e5dc55ad660e59
      client-secret: client_secret
      redirect-uri: redirect_uri
  provider:
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user

jwt:
  access-token:
    access-token-expire-length: expire-length

  refresh-token:
    refresh-token-expire-length: expire-length

  token:
    secret-key: secret-key
    signature-algorithm: signature-algorithm

